### ISSUE TITLE
Inventory interactions are not functional on all protocols

### ISSUE THREAD

**Issue by ghost** [DarkStorm652/DarkBot#10]
Inventory interactions were broken by the transition to external protocol handling. All attempts to move things in inventory via packet 102 result in transactions (via packet 106) to be not accepted.
(Edited by DarkStorm for actual bug causing previously reported issue below)

Sorry if this is too much but can the inventory management be improved to match nocheat's standard? When farming, my bot can't store the items in the chest because it's clicking too fast. Also, it is next to impossible for the bot to equip armor, drop items and drop inventory because of that.

If you don't have any idea of what I'm talking about, I mean something like WeepCraft's dropping mechanic where there is a slight delay between each item stack.

**Comment by DarkStorm652** [comment]
Fixed in https://github.com/DarkStorm652/DarkBot/commit/5f61dfadd1286b5b99da4366372cd09ebe709fda
