### ISSUE TITLE
Update protocol to 1.7

### ISSUE THREAD

**Issue by opl-** [DarkStorm652/DarkBot#18]
Currently protocol is only for 1.5 and 1.6 versions of Minecraft. Update would be really nice, even though you didn't commit anything to this project for 4 months...

**Comment by LefsFlare** [comment]
I've got a feeling this project's dead.

**Comment by DarkStorm652** [comment]
Temporarily on hiatus (at least for my updates). Significant progress has been made toward this item, but there are still missing portions. I will push the work that has been done sometime soon.

**Comment by LefsFlare** [comment]
Music to my ears Dark!

If you managed to keep it updated this time around, maybe I'll drop you a donation?

**Comment by LefsFlare** [comment]
Also, DarkStorm, please try not to make any empty promises, as far as I can tell, the last update was 6 months ago, if there was any progress, please show us, we are losing hope over here... This was pretty much the only working Minecraft bot in the 1.6.4 days, I don't want to see it die out.

If you need any help in updating, do at least inform us a little!

**Comment by opl-** [comment]
Great to hear that this project is not dead! Hopefully you will update it to 1.7 protocol before 1.8 comes out, as I would really like to start playing with it, as it seems like a good way to learn how to code AI's.

**Comment by DarkStorm652** [comment]
Progress is being made! https://github.com/DarkStorm652/DarkBot/commit/09c7bdc53d040aced7b305441ecf8edf1e173fb0

All of the changes are being made in the development branch, if you want to head over and see.

**Comment by DarkStorm652** [comment]
Well, that was an obvious fix! Movement works and so does 1.7! Merged it into the main branch.

https://github.com/DarkStorm652/DarkBot/commit/073081d71cb2fdf877629c433924f8426dcb4693
