### ISSUE TITLE
Payment

### ISSUE THREAD

**Issue by LefsFlare** [DarkStorm652/DarkBot#21]
Hey DarkStorm652,

Since you finally started re-coding DarkBot, can I have your PayPal email? I'll drop you funds for a coffee :)

**Comment by LefsFlare** [comment]
Is the bot actually functioning in 1.7.x now? Will coding continue for 1.7.8? Any bugs left unsquashed?

**Comment by DarkStorm652** [comment]
Hey! 1.7.2 is up! Dropped you my paypal via email; thanks a bunch in advance!
