### ISSUE TITLE
BlockChangeEvent fired with coordinates of block within chunk

### ISSUE THREAD

**Issue by opl-** [DarkStorm652/DarkBot#22]
In some cases the BlockChangeEvent is fired with wrong coordinates. In many cases these coordinates appear to be block coordinates within chunks. It happened in these cases:

<ul>
<li>When a block with other block attached to it is destroyed both of these block fire BlockChangeEvent with chunk coordinates.</li>
<li>When interacting with blocks that are close to the player.</li>
</ul>

**Comment by DarkStorm652** [comment]
This explains a lot... including that the protocol system really needs to conform to DRY.

**Comment by t81lal** [comment]
i think the protocl version is fine
i even modelled my own around the system http://λ.pw/gdk
i think the problem is the api needs to be protocol specific because the version changes are too significant to allow for a multi version compatible system

**Comment by DarkStorm652** [comment]
Nah, protocols just need to represent only their changes from the previous version, rather than being completely new implementations. The change will require some work, but it will make updating much less of a hassle in the future.

**Comment by t81lal** [comment]
a lot changed from 1.7 to 1.8 if u look at it in the long run would it always remain backwards compatible?

**Comment by DarkStorm652** [comment]
No amount of changes warrants creating a copy of the code of a previous (and potentially buggy) protocol version. It would be much better if bug fixes to an older protocol version fixed the same bugs that transitioned over in newer protocol versions without having to make the change in all of them separately.

**Comment by DarkStorm652** [comment]
My lord how disguised this was. Damn low precedences of bitwise operators! *mutters angrily

https://github.com/DarkStorm652/DarkBot/commit/13e6fe0d093321c015501a4a987f4f39d152f047
