### ISSUE TITLE
False alarm

### ISSUE THREAD

**Issue by LefsFlare** [DarkStorm652/DarkBot#31]
Just to put it out there to those who are busy hoping for an update from the creator. I have bad news for all of you. Dark, also known as Robbin was part of a fatal car accident. He will be forever remembered by his family and friends. The culprit is still at large.

**Comment by Unihedro** [comment]
I am very sorry to hear this, LefsFlare!

**Comment by SorenKitsune** [comment]
Where did you hear this?

**Comment by Unihedro** [comment]
@sk8er92749: DarkStorm is watching the repository and gets email notifications for every ticket, so if it's not true he would be replying by now...

**Comment by SorenKitsune** [comment]
He never responds to tickets anymore though. I'm not sure if LefsFlare is messing with us or not :/

**Comment by DarkStorm652** [comment]
Damit LefsFlare. :angry:

Sorry for the inactivity on this project, guys. Minecraft updates are quite the time commitment and I've been busy with school :cry: It's also not very motivating that many tasks stop functioning between updates. I will devote myself to making at least one update each week, starting with an update to 1.8!

**Comment by Unihedro** [comment]
^^^^^^^ aha

**Comment by LefsFlare** [comment]
It worked didn't it? Don't blame me for drastic measures.

**Comment by DarkStorm652** [comment]
I can do it this time!

**Comment by SorenKitsune** [comment]
@DarkStorm652 good luck!

**Comment by SorenKitsune** [comment]
@DarkStorm652 So about the updates, will it be weekly updates that'll be progress to the 1.8 update or a full 1.8 update tomorrow?

**Comment by DarkStorm652** [comment]
Progress towards 1.8 in the development branch. It should not take long, but I've made a few significant breakthroughs in the design of a new Minecraft swarm intelligence system that I'm going to start working on at the same time. (That project will eventually replace this one.)

**Comment by SorenKitsune** [comment]
Alright. Glad you're back dude.

**Comment by InternetPerson** [comment]
@DarkStorm652 you're not updating this are you? :l

**Comment by TheBiblMan** [comment]
@InternetPerson we currently have a large issue we're working
"20/12/2014 04:13:12 ᴅᴀɴᴋsᴛᴏʀᴍ ( ͡۝ ͜ʖ ͡۝): i wish to activate the minceraft

**Comment by InternetPerson** [comment]
@TheBiblMan wow, that's a very very large issue!

**Comment by DarkStorm652** [comment]
@InternetPerson it's support for slabs, stairs, and entity velocities and much improved movement all in one

**Comment by SorenKitsune** [comment]
So when will Darkstorm figure out how to activate the minceraft?

Edit: replied right as I posted this xD

**Comment by sk8er92749** [comment]
Oh, he replied right as I posted this xD

**Comment by InternetPerson** [comment]
well for now can you add support for plugins that modify network packets until you're finished updating it?

these plugins for example don't work with darkbot

http://www.spigotmc.org/resources/protocolsupport.2367/
http://www.spigotmc.org/resources/carbon.1258/

**Comment by DarkStorm652** [comment]
I'll look into it, thanks for pointing it out. Submit a separate issue for bookkeeping purposes, please!

**Comment by InternetPerson** [comment]
would be nice to have that until you update darkbot to 1.8 and okay I will

**Comment by TheBiblMan** [comment]
@InternetPerson  you could always go ahead and fork or pull 
then you'd realise how much work it is

**Comment by InternetPerson** [comment]
@TheBiblMan no thanks ;)

**Comment by DarkStorm652** [comment]
You can test out an alpha version of velocity-based motion: https://github.com/DarkStorm652/DarkBot/commit/a5ad4a0d671247c19b21f3498bc68da4f6c2c350

Just do a quick `git clone --branch development https://github.com/DarkStorm652/DarkBot` and `ant` and run `DarkBot.jar`
