### ISSUE TITLE
Proxy dont work!

### ISSUE THREAD

**Issue by mikigal** [DarkStorm652/DarkBot#40]
I have 4k proxies servers. But i can't register bots on server, beacouse I can register only 1 acount per 1 IP. PROXY DONT WORK!

**Comment by Unihedro** [comment]
... So? This issue does not stand on its own, as there is no demand for using proxies.

**Comment by GlitchHead** [comment]
Your probably trying to use socks proxies its really weird when trying to use socks but anyways http or https proxies don't seem to have a problem for login. the socks proxy join thing is very weird for not just you but everyone i get a 30 socks proxy list checked and only 5 of the 30 socks proxys only work with bots joining. If you need working http proxies go on google and search "http proxy list" or get some program that leeches proxies.

**Comment by mikigal** [comment]
I using HTTP proxies

**Comment by DarkStorm652** [comment]
You shouldn't be using HTTP proxies to join a server.
