### ISSUE TITLE
Protocol support

### ISSUE THREAD

**Issue by SocketByte** [DarkStorm652/DarkBot#42]
Protocols does not work for me.

"No protocol support for v4/5/etc. found"

What should I do?

**Comment by Unihedro** [comment]
More details, please. Environment information and the version of the build you use. As of state, this ticket is no more than "it no works", it's pretty hard to help you or fix what's wrong.

**Comment by SocketByte** [comment]
I have newest version of DarkBot, Windows 7, Wi-Fi connection (very speed), IPv4, and IPv6.

I compiled DarkBot with Apache ant v1.9.4 and i have protocols (4 - 78).
My run code is: 
java -jar DarkBot.jar -t spambot -o MyNickname -s ServerIPandPort -O -b 350 -d 2500 --protocol 4 --http-proxy-list proxy.txt

Proxy file: http://pastebin.com/YKwNuLG8
Anything else? Because I do not really know what else might be affected.

PS: Sorry for my english, bro :c

**Comment by GlitchHead** [comment]
you dont need --http-proxy-list if the server is in Offline -O

**Comment by SocketByte** [comment]
Okey, but i have still error with protocol :/

**Comment by SocketByte** [comment]
Okey, i have not compiled protocols xD
Thanks anyway

**Comment by InternetPerson** [comment]
welp, darkstorm abandoned this again...

**Comment by TheBiblMan** [comment]
welp, people have better shit to do in their lives than to tend to some kids that want to cheat in a block game

**Comment by Unihedro** [comment]
But honestly, in the current state of the code and how much clean up has to go through for any sane implementation to carry on, I kind of understand why he's not motivated to continue. It's not like the bot has continuation value anymore now that fewer people are playing Minecraft after recent events.

```
cc @InternetPerson @TheBiblMan
```
