### ISSUE TITLE
What is the problem?

### ISSUE THREAD

**Issue by ElPresidentePro** [DarkStorm652/DarkBot#43]
Hello !!, sorr for my bad english ;)
I have error when connect the server the server is v 1.7.2
ERRORS:
[BOT] Connecting... [BOT] Error: Unable to connect (java.lang.NullPointerException)
This is of DarkBotMC Launcher and when use in cmd my console have millions errors
Pls i need help ;(

**Comment by ElPresidentePro** [comment]
http://gyazo.com/ee04c33054ca868d660eb3effeabd4d1 The console screenshot java error pls help!!!!

**Comment by GlitchHead** [comment]
try compiling darkbot again. what are you using for compiling?

**Comment by ElPresidentePro** [comment]
@GlitchHead Yes i try compiling but remains the same :(

**Comment by ElPresidentePro** [comment]
what java use? i compile whit power sell and ANT

**Comment by Unihedro** [comment]
> when use in cmd my console have millions errors

Please specify your environment and build specifications clearly. For instance, you're obviously using Windows. We can't fix anything by doing guesswork.

**Comment by ElPresidentePro** [comment]
ok sorry, what needs to teach?

**Comment by Unihedro** [comment]
I just said what you needed to tell us, no more, no less.

**Comment by DarkStorm652** [comment]
Don't use deprecated components. The GUI will be removed in a future update.
