### ISSUE TITLE
Command Build Schematic worked?

### ISSUE THREAD

**Issue by ElPresidentePro** [DarkStorm652/DarkBot#48]
How will the build command work?

Pls i need ;)

**Comment by Unihedro** [comment]
[What have you tried](http://whathaveyoutried.com) and how doesn't it work?

**Comment by GlitchHead** [comment]
this is [CHILD ABUSE](http://i.kinja-img.com/gawker-media/image/upload/s--F5lzmFHh--/ltvok29jwjkofad471q5.gif).

**Comment by ElPresidentePro** [comment]
@DarkStorm652 Does the build command schematic? & How does it work?

**Comment by DarkStorm652** [comment]
Nope, no schematic building, sorry. That command uses two coordinates representing two diagonal corner blocks of a rectangular prism area to mine out, though I believe it has been broken for some time now.

**Comment by ElPresidentePro** [comment]
@DarkStorm652 If that works, but I did not know was that if also building schematics
