### ISSUE TITLE
Compiling doesn't work?

### ISSUE THREAD

**Issue by PhanaticD** [DarkStorm652/DarkBot#52]
When I compile with the new gradle method I just get a emtpy 1kb jar file with "gradle build" Is it not fully set up yet or am I doing something wrong?

**Comment by DarkStorm652** [comment]
The development branch does not currently build. I'm in the process of rolling out version 2.0, which involves significant changes to the structure of the project.

**Comment by PhanaticD** [comment]
looking forward to it
