### ISSUE TITLE
Howto compile Development Branch

### ISSUE THREAD

**Issue by Techcable** [DarkStorm652/DarkBot#53]
What do i execute at the command line to compile the development branch?

**Comment by DarkStorm652** [comment]
MERRRP, take a look at the other closed issues on this topic.

**Comment by DarkStorm652** [comment]
On a side note, you can grab an older revision of the development branch.

**Comment by DarkStorm652** [comment]
This one should compile:

https://github.com/DarkStorm652/DarkBot/commit/8a7234b136e8d24d910c0d96c3f4b1fbd5691847
